// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {social} from '../models';
import {store} from '../models';
import {auth} from '../models';
import {main} from '../models';
import {extensions} from '../models';
import {embeddedplayer} from '../models';
import {time} from '../models';
import {torbox} from '../models';

export function AddExtensionRepository(arg1:string,arg2:string):Promise<void>;

export function AddFriendByCode(arg1:string):Promise<social.Friend>;

export function AddToFavorites(arg1:store.SavedAnime):Promise<boolean>;

export function AddToWatchHistory(arg1:store.WatchedEpisode):Promise<void>;

export function AssistirEpisodio(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AuthGetSeedingEnabled():Promise<boolean>;

export function AuthGetSession():Promise<auth.UserSession>;

export function AuthIsGuest():Promise<boolean>;

export function AuthIsLoggedIn():Promise<boolean>;

export function AuthLogin(arg1:string,arg2:string):Promise<auth.UserSession>;

export function AuthLoginAsGuest():Promise<auth.UserSession>;

export function AuthLogout():Promise<void>;

export function AuthRegister(arg1:string,arg2:string,arg3:string,arg4:string):Promise<auth.UserSession>;

export function AuthSetSeedingEnabled(arg1:boolean):Promise<void>;

export function BuscarAnimes(arg1:string):Promise<Array<store.SavedAnime>>;

export function BuscarAnimesMulti(arg1:Array<string>):Promise<Array<store.SavedAnime>>;

export function CheckExtensionUpdates():Promise<Record<string, string>>;

export function ClearAllCache():Promise<void>;

export function ClearEpisodesCache():Promise<void>;

export function ClearSocialWatchingStatus():Promise<void>;

export function CompleteDiscordOAuthWithCode(arg1:string):Promise<main.DiscordUserInfo>;

export function ConfigurePlayerSkipSegments(arg1:main.SkipTimesResult):Promise<void>;

export function ConnectDiscord(arg1:string):Promise<void>;

export function CreateSocialProfile(arg1:string):Promise<social.UserProfile>;

export function CreateUser(arg1:string,arg2:string):Promise<store.UserData>;

export function DeleteSocialProfile():Promise<void>;

export function DisconnectDiscord():Promise<void>;

export function DisconnectDiscordUser():Promise<void>;

export function DiscordRPCClear():Promise<void>;

export function DiscordRPCConnect():Promise<void>;

export function DiscordRPCDisconnect():Promise<void>;

export function DiscordRPCIsConnected():Promise<boolean>;

export function DiscordRPCSetWatching(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number):Promise<void>;

export function DiscordRPCUpdatePosition(arg1:number,arg2:boolean):Promise<void>;

export function ExportUserData():Promise<string>;

export function FetchRepositoryExtensions(arg1:string):Promise<Array<main.RemoteExtensionInfo>>;

export function FormatEpisodeTitle(arg1:string):Promise<string>;

export function GenerateDiscordLinkCode():Promise<string>;

export function GetAllMangaSources():Promise<Array<main.MangaSourceDetail>>;

export function GetAllMangas(arg1:number):Promise<main.MangaListResult>;

export function GetAllMangasAdult():Promise<Array<main.MangaInfo>>;

export function GetAllMangasComplete():Promise<Array<main.MangaInfo>>;

export function GetAllMangasFromSourceComplete(arg1:string):Promise<Array<main.MangaInfo>>;

export function GetAllMangasSafe():Promise<Array<main.MangaInfo>>;

export function GetAlternativeSource(arg1:Array<string>):Promise<string>;

export function GetAnimeHDImage(arg1:string):Promise<Record<string, string>>;

export function GetAnimePoster(arg1:string):Promise<string>;

export function GetAnimePostersMulti(arg1:Array<string>):Promise<Record<string, string>>;

export function GetAnimeSources():Promise<Array<string>>;

export function GetAnimeSourcesInfo():Promise<Array<main.AnimeSourceInfo>>;

export function GetAnimeURL(arg1:string):Promise<string>;

export function GetAvailableLanguages():Promise<Array<string>>;

export function GetCacheStats():Promise<main.CacheStats>;

export function GetChapterPages(arg1:string):Promise<Array<main.MangaPageInfo>>;

export function GetChapterPagesAuto(arg1:string):Promise<Array<main.MangaPageInfo>>;

export function GetConsumetEpisodes(arg1:string,arg2:string):Promise<Array<main.ConsumetEpisode>>;

export function GetConsumetStream(arg1:string,arg2:string):Promise<string>;

export function GetCurrentUser():Promise<store.UserData>;

export function GetDiscordConfigStatus():Promise<Record<string, any>>;

export function GetDiscordFriendsActivity():Promise<Array<main.DiscordFriendActivity>>;

export function GetDiscordLinkStatus():Promise<main.DiscordLinkInfo>;

export function GetDiscordOAuthURL():Promise<string>;

export function GetDiscordRecommendations():Promise<Array<main.DiscordRecommendation>>;

export function GetDiscordServerInvite():Promise<string>;

export function GetDiscordStatus():Promise<main.DiscordStatus>;

export function GetDiscordUser():Promise<main.DiscordUserInfo>;

export function GetEnabledMangaSources():Promise<Array<main.MangaSourceDetail>>;

export function GetEnimeStream(arg1:string,arg2:number):Promise<string>;

export function GetEpisodes(arg1:string):Promise<Array<store.Episode>>;

export function GetEpisodesForSource(arg1:string,arg2:string):Promise<Array<store.Episode>>;

export function GetExtensionAnimeDetails(arg1:string,arg2:string):Promise<extensions.AnimeDetails>;

export function GetExtensionEpisodes(arg1:string,arg2:string):Promise<Array<extensions.Episode>>;

export function GetExtensionLatest(arg1:string,arg2:number):Promise<Array<extensions.AnimeEntry>>;

export function GetExtensionRepositories():Promise<Array<main.RepositoryInfo>>;

export function GetExtensionVideoSources(arg1:string,arg2:string):Promise<Array<extensions.VideoSource>>;

export function GetFavorites():Promise<Array<store.SavedAnime>>;

export function GetFeaturedMangas(arg1:number):Promise<Array<main.MangaInfo>>;

export function GetFeaturedMangasFromSource(arg1:number,arg2:string):Promise<Array<main.MangaInfo>>;

export function GetFriendsActivity():Promise<Array<social.FriendActivity>>;

export function GetFriendsList():Promise<Array<social.Friend>>;

export function GetInstalledExtensions():Promise<Array<main.ExtensionInfo>>;

export function GetLatestMangas():Promise<Array<main.MangaInfo>>;

export function GetLatestMangasFromSource(arg1:string):Promise<Array<main.MangaInfo>>;

export function GetMangaChapters(arg1:string):Promise<Array<main.MangaChapterInfo>>;

export function GetMangaChaptersAuto(arg1:string):Promise<Array<main.MangaChapterInfo>>;

export function GetMangaDetails(arg1:string):Promise<main.MangaInfo>;

export function GetMangaDetailsAuto(arg1:string):Promise<main.MangaInfo>;

export function GetMangaGenres():Promise<Array<string>>;

export function GetMangaSources():Promise<Array<string>>;

export function GetMangaSourcesByLanguage(arg1:string):Promise<Array<main.MangaSourceDetail>>;

export function GetMangaSourcesInfo():Promise<Array<main.MangaSourceInfo>>;

export function GetMangasByGenre(arg1:string):Promise<Array<main.MangaInfo>>;

export function GetMangasFromAllSources(arg1:number):Promise<main.MangaListResult>;

export function GetMangasFromSource(arg1:string,arg2:number):Promise<main.MangaListResult>;

export function GetMergedMangas(arg1:number):Promise<Array<main.MangaInfo>>;

export function GetMergedMangasComplete():Promise<Array<main.MangaInfo>>;

export function GetMergedMangasWithBestSource():Promise<Array<main.MangaInfo>>;

export function GetPlayer4KModes():Promise<Array<main.QualityModeInfo>>;

export function GetPopularAnimes(arg1:number):Promise<Array<main.AniListAnime>>;

export function GetPopularMangas():Promise<Array<main.MangaInfo>>;

export function GetPopularMangasAdult():Promise<Array<main.MangaInfo>>;

export function GetPopularMangasAllSources():Promise<Array<main.MangaInfo>>;

export function GetPopularMangasFromSource(arg1:string):Promise<Array<main.MangaInfo>>;

export function GetPopularMangasSafe():Promise<Array<main.MangaInfo>>;

export function GetProxyURLForVideo(arg1:string):Promise<string>;

export function GetQualityModes():Promise<Array<main.QualityModeInfo>>;

export function GetSeedingStats():Promise<main.SeedingStats>;

export function GetSettings():Promise<store.UserSettings>;

export function GetSkipTimes(arg1:number,arg2:number):Promise<main.SkipTimesResult>;

export function GetSkipTimesAsync(arg1:number,arg2:number):Promise<void>;

export function GetSmartStream(arg1:string,arg2:number):Promise<main.SmartStreamResult>;

export function GetSmartStreamParallel(arg1:string,arg2:number):Promise<main.SmartStreamResult>;

export function GetSocialConnectionStatus():Promise<boolean|string>;

export function GetSocialProfile():Promise<social.UserProfile>;

export function GetStreamSourceStats():Promise<Record<string, any>>;

export function GetStreamURLForEpisode(arg1:string,arg2:string):Promise<string>;

export function GetStreamWithFallback(arg1:string,arg2:number):Promise<string>;

export function GetTopAnimes():Promise<Array<store.SavedAnime>>;

export function GetTorrentSources():Promise<Array<main.TorrentSource>>;

export function GetTrendingAnimes(arg1:number):Promise<Array<main.AniListAnime>>;

export function GetValidatedStreamCache(arg1:string):Promise<string|boolean>;

export function GetWatchHistory():Promise<Array<store.WatchedEpisode>>;

export function HasSocialProfile():Promise<boolean>;

export function ImportUserData(arg1:string):Promise<void>;

export function InitEmbeddedPlayer():Promise<void>;

export function InitRemoteConnection(arg1:string):Promise<boolean>;

export function InitTorBox(arg1:string):Promise<boolean>;

export function InstallExtension(arg1:string,arg2:string):Promise<void>;

export function InstallExtensionFromFile(arg1:string):Promise<void>;

export function InvalidateStreamCache(arg1:string):Promise<void>;

export function IsFavorite(arg1:string):Promise<boolean>;

export function IsMPVInstalled():Promise<boolean>;

export function IsMangaSourceEnabled(arg1:string):Promise<boolean>;

export function IsPlayer4KAvailable():Promise<boolean>;

export function IsSeedingRunning():Promise<boolean>;

export function IsSourceAvailable(arg1:string):Promise<boolean>;

export function IsTorBoxConfigured():Promise<boolean>;

export function LikeDiscordRecommendation(arg1:string):Promise<boolean>;

export function LinkDiscordWithCode(arg1:string):Promise<main.DiscordLinkInfo>;

export function ParseEpisodeFilenames(arg1:Array<string>):Promise<main.EpisodeGroupResultInfo>;

export function ParseEpisodeFilenamesJSON(arg1:Array<string>):Promise<string>;

export function ParseEpisodeFilenamesV2(arg1:Array<string>):Promise<main.EpisodeParseResultInfo>;

export function ParseSingleEpisodeFilename(arg1:string):Promise<main.ParsedEpisodeInfo>;

export function PlayAnime(arg1:string):Promise<void>;

export function PlayVideo(arg1:string,arg2:string):Promise<void>;

export function PlayWithPlayer4K(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function PlayWithPlayer4KTitle(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PlayWithPlayer4KTitleSub(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PlayerGetInfo():Promise<embeddedplayer.PlayerInfo>;

export function PlayerGetVolume():Promise<number>;

export function PlayerLoad(arg1:string,arg2:string):Promise<void>;

export function PlayerLoadSubtitle(arg1:string):Promise<void>;

export function PlayerPause():Promise<void>;

export function PlayerPlay():Promise<void>;

export function PlayerSeek(arg1:number):Promise<void>;

export function PlayerSeekRelative(arg1:number):Promise<void>;

export function PlayerSetAudioTrack(arg1:number):Promise<void>;

export function PlayerSetAutoSkip(arg1:boolean):Promise<void>;

export function PlayerSetICCProfile(arg1:string):Promise<void>;

export function PlayerSetICCProfileAuto(arg1:boolean):Promise<void>;

export function PlayerSetQuality(arg1:string):Promise<void>;

export function PlayerSetSpeed(arg1:number):Promise<void>;

export function PlayerSetSubtitleTrack(arg1:number):Promise<void>;

export function PlayerSetVolume(arg1:number):Promise<void>;

export function PlayerStop():Promise<void>;

export function PlayerToggle():Promise<void>;

export function PlayerToggleFullscreen():Promise<void>;

export function PlayerToggleMute():Promise<void>;

export function RegenerateSocialShareCode():Promise<string>;

export function RemoteCleanupTorrents(arg1:number):Promise<number>;

export function RemoteDeleteTorrent(arg1:number):Promise<boolean>;

export function RemoteGetEpisodes(arg1:number):Promise<Array<main.RemoteEpisodeInfo>>;

export function RemoteGetRecentReleases(arg1:number):Promise<Array<main.RemoteAnimeInfo>>;

export function RemoteGetStreamLink(arg1:string,arg2:number):Promise<main.RemoteStreamLink>;

export function RemoteGetStreamLinkWithTorrent(arg1:string,arg2:number,arg3:number):Promise<main.RemoteStreamLink>;

export function RemoteGetTorrentFiles(arg1:string,arg2:string):Promise<main.RemoteTorrentInfo>;

export function RemoteGetTorrentFilesRetry(arg1:number):Promise<main.RemoteTorrentInfo>;

export function RemoteGetTorrentFilesWithPolling(arg1:number,arg2:time.Duration):Promise<main.RemoteTorrentInfo>;

export function RemoteHealthCheck():Promise<boolean>;

export function RemoteListTorrents():Promise<Array<main.RemoteTorrentInfo>>;

export function RemoteProcessEpisode(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:boolean):Promise<main.PipelineResult>;

export function RemoteSearchAnimes(arg1:string):Promise<Array<main.RemoteAnimeInfo>>;

export function RemoteSearchTorrents(arg1:string,arg2:boolean):Promise<Array<main.RemoteTorrentResult>>;

export function RemoveExtensionRepository(arg1:string):Promise<void>;

export function RemoveFriend(arg1:string):Promise<void>;

export function RemoveFromFavorites(arg1:string):Promise<boolean>;

export function ResetMangaSources():Promise<void>;

export function ResetSourceFailures():Promise<void>;

export function ResetStreamCircuits():Promise<void>;

export function SaveDiscordConfig(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:store.UserSettings):Promise<boolean>;

export function SearchAniList(arg1:string,arg2:number):Promise<Array<main.AniListAnime>>;

export function SearchConsumet(arg1:string):Promise<Array<main.ConsumetAnime>>;

export function SearchEnime(arg1:string):Promise<Array<main.EnimeAnime>>;

export function SearchMangas(arg1:string):Promise<Array<main.MangaInfo>>;

export function SearchMangasAllSources(arg1:string):Promise<Array<main.MangaInfo>>;

export function SearchMangasFromSource(arg1:string,arg2:string):Promise<Array<main.MangaInfo>>;

export function SearchTorrents(arg1:string,arg2:string):Promise<Array<main.TorrentResult>>;

export function SearchTorrentsAll(arg1:string):Promise<Array<main.TorrentResult>>;

export function SearchTorrentsBR(arg1:string):Promise<Array<main.TorrentResult>>;

export function SearchTorrentsNyaa(arg1:string):Promise<Array<main.TorrentResult>>;

export function SearchWithExtension(arg1:string,arg2:string,arg3:number):Promise<Array<extensions.AnimeEntry>>;

export function SendDiscordRecommendation(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function SetDiscordClientSecret(arg1:string):Promise<void>;

export function SetDiscordShareAnimes(arg1:boolean):Promise<void>;

export function SetDiscordShowStatus(arg1:boolean):Promise<void>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function SetSocialShareAnimes(arg1:boolean):Promise<void>;

export function SetSocialShowStatus(arg1:boolean):Promise<void>;

export function SetStreamCache(arg1:string,arg2:string,arg3:string,arg4:time.Duration):Promise<void>;

export function SimulateDiscordConnect():Promise<void>;

export function SkipEnding():Promise<void>;

export function SkipOpening():Promise<void>;

export function StartDiscordOAuth():Promise<void>;

export function StartSeeding():Promise<void>;

export function StopPlayer4K():Promise<void>;

export function StopSeeding():Promise<void>;

export function SyncSocialWithServer():Promise<void>;

export function ToggleExtension(arg1:string,arg2:boolean):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function ToggleMangaSource(arg1:string,arg2:boolean):Promise<void>;

export function ToggleSeeding(arg1:boolean):Promise<void>;

export function TorBoxAddMagnet(arg1:string):Promise<torbox.Torrent>;

export function TorBoxCheckCached(arg1:Array<string>):Promise<Record<string, boolean>>;

export function TorBoxClearCache():Promise<void>;

export function TorBoxDeleteTorrent(arg1:number):Promise<boolean>;

export function TorBoxGetDownloadLink(arg1:number,arg2:number):Promise<string>;

export function TorBoxGetFileStreamURL(arg1:number,arg2:number):Promise<string>;

export function TorBoxGetFilesFromMagnet(arg1:string):Promise<main.TorBoxTorrentInfo>;

export function TorBoxGetInstantStream(arg1:string):Promise<torbox.InstantStreamResult>;

export function TorBoxGetStreamLinkLocal(arg1:number,arg2:number):Promise<string>;

export function TorBoxGetTorrentFiles(arg1:string,arg2:string):Promise<main.TorBoxTorrentInfo>;

export function TorBoxGetTorrents():Promise<Array<torbox.Torrent>>;

export function TorBoxGetUser():Promise<torbox.User>;

export function TorBoxSearchAnimes(arg1:string):Promise<Array<main.TorBoxAnimeResult>>;

export function TorBoxSearchTorrents(arg1:string):Promise<Array<torbox.AnimeTorrent>>;

export function TorBoxStreamAnimeEpisode(arg1:string,arg2:number,arg3:string):Promise<torbox.InstantStreamResult>;

export function TorBoxStreamMagnet(arg1:string,arg2:string):Promise<string>;

export function UninstallExtension(arg1:string):Promise<void>;

export function UnlinkDiscord():Promise<void>;

export function UpdateDiscordWatchingStatus(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function UpdateSocialUsername(arg1:string):Promise<void>;

export function UpdateSocialWatchingStatus(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function VPSCheckHealth():Promise<boolean>;

export function VPSDownloadSubtitle(arg1:string,arg2:string):Promise<Array<number>>;

export function VPSGetBestSubtitle(arg1:string,arg2:number):Promise<main.SubtitleSearchResult>;

export function VPSGetEpisodeGoFile(arg1:string,arg2:number):Promise<string>;

export function VPSGetStreamURL(arg1:string):Promise<string>;

export function VPSSearchStream(arg1:string):Promise<main.VPSSearchResult>;

export function VPSSearchSubtitles(arg1:string,arg2:number):Promise<main.SubtitleSearchResponse>;

export function VPSStartPipeline(arg1:string,arg2:boolean,arg3:boolean):Promise<main.VPSPipelineResponse>;

export function ValidateStreamURL(arg1:string):Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowUnmaximise():Promise<void>;
