// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExtensionRepository(arg1, arg2) {
  return window['go']['main']['App']['AddExtensionRepository'](arg1, arg2);
}

export function AddFriendByCode(arg1) {
  return window['go']['main']['App']['AddFriendByCode'](arg1);
}

export function AddToFavorites(arg1) {
  return window['go']['main']['App']['AddToFavorites'](arg1);
}

export function AddToWatchHistory(arg1) {
  return window['go']['main']['App']['AddToWatchHistory'](arg1);
}

export function AssistirEpisodio(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssistirEpisodio'](arg1, arg2, arg3);
}

export function AuthGetSeedingEnabled() {
  return window['go']['main']['App']['AuthGetSeedingEnabled']();
}

export function AuthGetSession() {
  return window['go']['main']['App']['AuthGetSession']();
}

export function AuthIsGuest() {
  return window['go']['main']['App']['AuthIsGuest']();
}

export function AuthIsLoggedIn() {
  return window['go']['main']['App']['AuthIsLoggedIn']();
}

export function AuthLogin(arg1, arg2) {
  return window['go']['main']['App']['AuthLogin'](arg1, arg2);
}

export function AuthLoginAsGuest() {
  return window['go']['main']['App']['AuthLoginAsGuest']();
}

export function AuthLogout() {
  return window['go']['main']['App']['AuthLogout']();
}

export function AuthRegister(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AuthRegister'](arg1, arg2, arg3, arg4);
}

export function AuthSetSeedingEnabled(arg1) {
  return window['go']['main']['App']['AuthSetSeedingEnabled'](arg1);
}

export function BuscarAnimes(arg1) {
  return window['go']['main']['App']['BuscarAnimes'](arg1);
}

export function BuscarAnimesMulti(arg1) {
  return window['go']['main']['App']['BuscarAnimesMulti'](arg1);
}

export function CheckExtensionUpdates() {
  return window['go']['main']['App']['CheckExtensionUpdates']();
}

export function ClearAllCache() {
  return window['go']['main']['App']['ClearAllCache']();
}

export function ClearEpisodesCache() {
  return window['go']['main']['App']['ClearEpisodesCache']();
}

export function ClearSocialWatchingStatus() {
  return window['go']['main']['App']['ClearSocialWatchingStatus']();
}

export function CompleteDiscordOAuthWithCode(arg1) {
  return window['go']['main']['App']['CompleteDiscordOAuthWithCode'](arg1);
}

export function ConfigurePlayerSkipSegments(arg1) {
  return window['go']['main']['App']['ConfigurePlayerSkipSegments'](arg1);
}

export function ConnectDiscord(arg1) {
  return window['go']['main']['App']['ConnectDiscord'](arg1);
}

export function CreateSocialProfile(arg1) {
  return window['go']['main']['App']['CreateSocialProfile'](arg1);
}

export function CreateUser(arg1, arg2) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2);
}

export function DeleteSocialProfile() {
  return window['go']['main']['App']['DeleteSocialProfile']();
}

export function DisconnectDiscord() {
  return window['go']['main']['App']['DisconnectDiscord']();
}

export function DisconnectDiscordUser() {
  return window['go']['main']['App']['DisconnectDiscordUser']();
}

export function DiscordRPCClear() {
  return window['go']['main']['App']['DiscordRPCClear']();
}

export function DiscordRPCConnect() {
  return window['go']['main']['App']['DiscordRPCConnect']();
}

export function DiscordRPCDisconnect() {
  return window['go']['main']['App']['DiscordRPCDisconnect']();
}

export function DiscordRPCIsConnected() {
  return window['go']['main']['App']['DiscordRPCIsConnected']();
}

export function DiscordRPCSetWatching(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DiscordRPCSetWatching'](arg1, arg2, arg3, arg4, arg5);
}

export function DiscordRPCUpdatePosition(arg1, arg2) {
  return window['go']['main']['App']['DiscordRPCUpdatePosition'](arg1, arg2);
}

export function ExportUserData() {
  return window['go']['main']['App']['ExportUserData']();
}

export function FetchRepositoryExtensions(arg1) {
  return window['go']['main']['App']['FetchRepositoryExtensions'](arg1);
}

export function FormatEpisodeTitle(arg1) {
  return window['go']['main']['App']['FormatEpisodeTitle'](arg1);
}

export function GenerateDiscordLinkCode() {
  return window['go']['main']['App']['GenerateDiscordLinkCode']();
}

export function GetAllMangaSources() {
  return window['go']['main']['App']['GetAllMangaSources']();
}

export function GetAllMangas(arg1) {
  return window['go']['main']['App']['GetAllMangas'](arg1);
}

export function GetAllMangasAdult() {
  return window['go']['main']['App']['GetAllMangasAdult']();
}

export function GetAllMangasComplete() {
  return window['go']['main']['App']['GetAllMangasComplete']();
}

export function GetAllMangasFromSourceComplete(arg1) {
  return window['go']['main']['App']['GetAllMangasFromSourceComplete'](arg1);
}

export function GetAllMangasSafe() {
  return window['go']['main']['App']['GetAllMangasSafe']();
}

export function GetAlternativeSource(arg1) {
  return window['go']['main']['App']['GetAlternativeSource'](arg1);
}

export function GetAnimeHDImage(arg1) {
  return window['go']['main']['App']['GetAnimeHDImage'](arg1);
}

export function GetAnimePoster(arg1) {
  return window['go']['main']['App']['GetAnimePoster'](arg1);
}

export function GetAnimePostersMulti(arg1) {
  return window['go']['main']['App']['GetAnimePostersMulti'](arg1);
}

export function GetAnimeSources() {
  return window['go']['main']['App']['GetAnimeSources']();
}

export function GetAnimeSourcesInfo() {
  return window['go']['main']['App']['GetAnimeSourcesInfo']();
}

export function GetAnimeURL(arg1) {
  return window['go']['main']['App']['GetAnimeURL'](arg1);
}

export function GetAvailableLanguages() {
  return window['go']['main']['App']['GetAvailableLanguages']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetChapterPages(arg1) {
  return window['go']['main']['App']['GetChapterPages'](arg1);
}

export function GetChapterPagesAuto(arg1) {
  return window['go']['main']['App']['GetChapterPagesAuto'](arg1);
}

export function GetConsumetEpisodes(arg1, arg2) {
  return window['go']['main']['App']['GetConsumetEpisodes'](arg1, arg2);
}

export function GetConsumetStream(arg1, arg2) {
  return window['go']['main']['App']['GetConsumetStream'](arg1, arg2);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDiscordConfigStatus() {
  return window['go']['main']['App']['GetDiscordConfigStatus']();
}

export function GetDiscordFriendsActivity() {
  return window['go']['main']['App']['GetDiscordFriendsActivity']();
}

export function GetDiscordLinkStatus() {
  return window['go']['main']['App']['GetDiscordLinkStatus']();
}

export function GetDiscordOAuthURL() {
  return window['go']['main']['App']['GetDiscordOAuthURL']();
}

export function GetDiscordRecommendations() {
  return window['go']['main']['App']['GetDiscordRecommendations']();
}

export function GetDiscordServerInvite() {
  return window['go']['main']['App']['GetDiscordServerInvite']();
}

export function GetDiscordStatus() {
  return window['go']['main']['App']['GetDiscordStatus']();
}

export function GetDiscordUser() {
  return window['go']['main']['App']['GetDiscordUser']();
}

export function GetEnabledMangaSources() {
  return window['go']['main']['App']['GetEnabledMangaSources']();
}

export function GetEnimeStream(arg1, arg2) {
  return window['go']['main']['App']['GetEnimeStream'](arg1, arg2);
}

export function GetEpisodes(arg1) {
  return window['go']['main']['App']['GetEpisodes'](arg1);
}

export function GetEpisodesForSource(arg1, arg2) {
  return window['go']['main']['App']['GetEpisodesForSource'](arg1, arg2);
}

export function GetExtensionAnimeDetails(arg1, arg2) {
  return window['go']['main']['App']['GetExtensionAnimeDetails'](arg1, arg2);
}

export function GetExtensionEpisodes(arg1, arg2) {
  return window['go']['main']['App']['GetExtensionEpisodes'](arg1, arg2);
}

export function GetExtensionLatest(arg1, arg2) {
  return window['go']['main']['App']['GetExtensionLatest'](arg1, arg2);
}

export function GetExtensionRepositories() {
  return window['go']['main']['App']['GetExtensionRepositories']();
}

export function GetExtensionVideoSources(arg1, arg2) {
  return window['go']['main']['App']['GetExtensionVideoSources'](arg1, arg2);
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetFeaturedMangas(arg1) {
  return window['go']['main']['App']['GetFeaturedMangas'](arg1);
}

export function GetFeaturedMangasFromSource(arg1, arg2) {
  return window['go']['main']['App']['GetFeaturedMangasFromSource'](arg1, arg2);
}

export function GetFriendsActivity() {
  return window['go']['main']['App']['GetFriendsActivity']();
}

export function GetFriendsList() {
  return window['go']['main']['App']['GetFriendsList']();
}

export function GetInstalledExtensions() {
  return window['go']['main']['App']['GetInstalledExtensions']();
}

export function GetLatestMangas() {
  return window['go']['main']['App']['GetLatestMangas']();
}

export function GetLatestMangasFromSource(arg1) {
  return window['go']['main']['App']['GetLatestMangasFromSource'](arg1);
}

export function GetMangaChapters(arg1) {
  return window['go']['main']['App']['GetMangaChapters'](arg1);
}

export function GetMangaChaptersAuto(arg1) {
  return window['go']['main']['App']['GetMangaChaptersAuto'](arg1);
}

export function GetMangaDetails(arg1) {
  return window['go']['main']['App']['GetMangaDetails'](arg1);
}

export function GetMangaDetailsAuto(arg1) {
  return window['go']['main']['App']['GetMangaDetailsAuto'](arg1);
}

export function GetMangaGenres() {
  return window['go']['main']['App']['GetMangaGenres']();
}

export function GetMangaSources() {
  return window['go']['main']['App']['GetMangaSources']();
}

export function GetMangaSourcesByLanguage(arg1) {
  return window['go']['main']['App']['GetMangaSourcesByLanguage'](arg1);
}

export function GetMangaSourcesInfo() {
  return window['go']['main']['App']['GetMangaSourcesInfo']();
}

export function GetMangasByGenre(arg1) {
  return window['go']['main']['App']['GetMangasByGenre'](arg1);
}

export function GetMangasFromAllSources(arg1) {
  return window['go']['main']['App']['GetMangasFromAllSources'](arg1);
}

export function GetMangasFromSource(arg1, arg2) {
  return window['go']['main']['App']['GetMangasFromSource'](arg1, arg2);
}

export function GetMergedMangas(arg1) {
  return window['go']['main']['App']['GetMergedMangas'](arg1);
}

export function GetMergedMangasComplete() {
  return window['go']['main']['App']['GetMergedMangasComplete']();
}

export function GetMergedMangasWithBestSource() {
  return window['go']['main']['App']['GetMergedMangasWithBestSource']();
}

export function GetPlayer4KModes() {
  return window['go']['main']['App']['GetPlayer4KModes']();
}

export function GetPopularAnimes(arg1) {
  return window['go']['main']['App']['GetPopularAnimes'](arg1);
}

export function GetPopularMangas() {
  return window['go']['main']['App']['GetPopularMangas']();
}

export function GetPopularMangasAdult() {
  return window['go']['main']['App']['GetPopularMangasAdult']();
}

export function GetPopularMangasAllSources() {
  return window['go']['main']['App']['GetPopularMangasAllSources']();
}

export function GetPopularMangasFromSource(arg1) {
  return window['go']['main']['App']['GetPopularMangasFromSource'](arg1);
}

export function GetPopularMangasSafe() {
  return window['go']['main']['App']['GetPopularMangasSafe']();
}

export function GetProxyURLForVideo(arg1) {
  return window['go']['main']['App']['GetProxyURLForVideo'](arg1);
}

export function GetQualityModes() {
  return window['go']['main']['App']['GetQualityModes']();
}

export function GetSeedingStats() {
  return window['go']['main']['App']['GetSeedingStats']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkipTimes(arg1, arg2) {
  return window['go']['main']['App']['GetSkipTimes'](arg1, arg2);
}

export function GetSkipTimesAsync(arg1, arg2) {
  return window['go']['main']['App']['GetSkipTimesAsync'](arg1, arg2);
}

export function GetSmartStream(arg1, arg2) {
  return window['go']['main']['App']['GetSmartStream'](arg1, arg2);
}

export function GetSmartStreamParallel(arg1, arg2) {
  return window['go']['main']['App']['GetSmartStreamParallel'](arg1, arg2);
}

export function GetSocialConnectionStatus() {
  return window['go']['main']['App']['GetSocialConnectionStatus']();
}

export function GetSocialProfile() {
  return window['go']['main']['App']['GetSocialProfile']();
}

export function GetStreamSourceStats() {
  return window['go']['main']['App']['GetStreamSourceStats']();
}

export function GetStreamURLForEpisode(arg1, arg2) {
  return window['go']['main']['App']['GetStreamURLForEpisode'](arg1, arg2);
}

export function GetStreamWithFallback(arg1, arg2) {
  return window['go']['main']['App']['GetStreamWithFallback'](arg1, arg2);
}

export function GetTopAnimes() {
  return window['go']['main']['App']['GetTopAnimes']();
}

export function GetTorrentSources() {
  return window['go']['main']['App']['GetTorrentSources']();
}

export function GetTrendingAnimes(arg1) {
  return window['go']['main']['App']['GetTrendingAnimes'](arg1);
}

export function GetValidatedStreamCache(arg1) {
  return window['go']['main']['App']['GetValidatedStreamCache'](arg1);
}

export function GetWatchHistory() {
  return window['go']['main']['App']['GetWatchHistory']();
}

export function HasSocialProfile() {
  return window['go']['main']['App']['HasSocialProfile']();
}

export function ImportUserData(arg1) {
  return window['go']['main']['App']['ImportUserData'](arg1);
}

export function InitEmbeddedPlayer() {
  return window['go']['main']['App']['InitEmbeddedPlayer']();
}

export function InitRemoteConnection(arg1) {
  return window['go']['main']['App']['InitRemoteConnection'](arg1);
}

export function InitTorBox(arg1) {
  return window['go']['main']['App']['InitTorBox'](arg1);
}

export function InstallExtension(arg1, arg2) {
  return window['go']['main']['App']['InstallExtension'](arg1, arg2);
}

export function InstallExtensionFromFile(arg1) {
  return window['go']['main']['App']['InstallExtensionFromFile'](arg1);
}

export function InvalidateStreamCache(arg1) {
  return window['go']['main']['App']['InvalidateStreamCache'](arg1);
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function IsMPVInstalled() {
  return window['go']['main']['App']['IsMPVInstalled']();
}

export function IsMangaSourceEnabled(arg1) {
  return window['go']['main']['App']['IsMangaSourceEnabled'](arg1);
}

export function IsPlayer4KAvailable() {
  return window['go']['main']['App']['IsPlayer4KAvailable']();
}

export function IsSeedingRunning() {
  return window['go']['main']['App']['IsSeedingRunning']();
}

export function IsSourceAvailable(arg1) {
  return window['go']['main']['App']['IsSourceAvailable'](arg1);
}

export function IsTorBoxConfigured() {
  return window['go']['main']['App']['IsTorBoxConfigured']();
}

export function LikeDiscordRecommendation(arg1) {
  return window['go']['main']['App']['LikeDiscordRecommendation'](arg1);
}

export function LinkDiscordWithCode(arg1) {
  return window['go']['main']['App']['LinkDiscordWithCode'](arg1);
}

export function ParseEpisodeFilenames(arg1) {
  return window['go']['main']['App']['ParseEpisodeFilenames'](arg1);
}

export function ParseEpisodeFilenamesJSON(arg1) {
  return window['go']['main']['App']['ParseEpisodeFilenamesJSON'](arg1);
}

export function ParseEpisodeFilenamesV2(arg1) {
  return window['go']['main']['App']['ParseEpisodeFilenamesV2'](arg1);
}

export function ParseSingleEpisodeFilename(arg1) {
  return window['go']['main']['App']['ParseSingleEpisodeFilename'](arg1);
}

export function PlayAnime(arg1) {
  return window['go']['main']['App']['PlayAnime'](arg1);
}

export function PlayVideo(arg1, arg2) {
  return window['go']['main']['App']['PlayVideo'](arg1, arg2);
}

export function PlayWithPlayer4K(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlayWithPlayer4K'](arg1, arg2, arg3);
}

export function PlayWithPlayer4KTitle(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlayWithPlayer4KTitle'](arg1, arg2, arg3);
}

export function PlayWithPlayer4KTitleSub(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PlayWithPlayer4KTitleSub'](arg1, arg2, arg3, arg4);
}

export function PlayerGetInfo() {
  return window['go']['main']['App']['PlayerGetInfo']();
}

export function PlayerGetVolume() {
  return window['go']['main']['App']['PlayerGetVolume']();
}

export function PlayerLoad(arg1, arg2) {
  return window['go']['main']['App']['PlayerLoad'](arg1, arg2);
}

export function PlayerLoadSubtitle(arg1) {
  return window['go']['main']['App']['PlayerLoadSubtitle'](arg1);
}

export function PlayerPause() {
  return window['go']['main']['App']['PlayerPause']();
}

export function PlayerPlay() {
  return window['go']['main']['App']['PlayerPlay']();
}

export function PlayerSeek(arg1) {
  return window['go']['main']['App']['PlayerSeek'](arg1);
}

export function PlayerSeekRelative(arg1) {
  return window['go']['main']['App']['PlayerSeekRelative'](arg1);
}

export function PlayerSetAudioTrack(arg1) {
  return window['go']['main']['App']['PlayerSetAudioTrack'](arg1);
}

export function PlayerSetAutoSkip(arg1) {
  return window['go']['main']['App']['PlayerSetAutoSkip'](arg1);
}

export function PlayerSetICCProfile(arg1) {
  return window['go']['main']['App']['PlayerSetICCProfile'](arg1);
}

export function PlayerSetICCProfileAuto(arg1) {
  return window['go']['main']['App']['PlayerSetICCProfileAuto'](arg1);
}

export function PlayerSetQuality(arg1) {
  return window['go']['main']['App']['PlayerSetQuality'](arg1);
}

export function PlayerSetSpeed(arg1) {
  return window['go']['main']['App']['PlayerSetSpeed'](arg1);
}

export function PlayerSetSubtitleTrack(arg1) {
  return window['go']['main']['App']['PlayerSetSubtitleTrack'](arg1);
}

export function PlayerSetVolume(arg1) {
  return window['go']['main']['App']['PlayerSetVolume'](arg1);
}

export function PlayerStop() {
  return window['go']['main']['App']['PlayerStop']();
}

export function PlayerToggle() {
  return window['go']['main']['App']['PlayerToggle']();
}

export function PlayerToggleFullscreen() {
  return window['go']['main']['App']['PlayerToggleFullscreen']();
}

export function PlayerToggleMute() {
  return window['go']['main']['App']['PlayerToggleMute']();
}

export function RegenerateSocialShareCode() {
  return window['go']['main']['App']['RegenerateSocialShareCode']();
}

export function RemoteCleanupTorrents(arg1) {
  return window['go']['main']['App']['RemoteCleanupTorrents'](arg1);
}

export function RemoteDeleteTorrent(arg1) {
  return window['go']['main']['App']['RemoteDeleteTorrent'](arg1);
}

export function RemoteGetEpisodes(arg1) {
  return window['go']['main']['App']['RemoteGetEpisodes'](arg1);
}

export function RemoteGetRecentReleases(arg1) {
  return window['go']['main']['App']['RemoteGetRecentReleases'](arg1);
}

export function RemoteGetStreamLink(arg1, arg2) {
  return window['go']['main']['App']['RemoteGetStreamLink'](arg1, arg2);
}

export function RemoteGetStreamLinkWithTorrent(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteGetStreamLinkWithTorrent'](arg1, arg2, arg3);
}

export function RemoteGetTorrentFiles(arg1, arg2) {
  return window['go']['main']['App']['RemoteGetTorrentFiles'](arg1, arg2);
}

export function RemoteGetTorrentFilesRetry(arg1) {
  return window['go']['main']['App']['RemoteGetTorrentFilesRetry'](arg1);
}

export function RemoteGetTorrentFilesWithPolling(arg1, arg2) {
  return window['go']['main']['App']['RemoteGetTorrentFilesWithPolling'](arg1, arg2);
}

export function RemoteHealthCheck() {
  return window['go']['main']['App']['RemoteHealthCheck']();
}

export function RemoteListTorrents() {
  return window['go']['main']['App']['RemoteListTorrents']();
}

export function RemoteProcessEpisode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RemoteProcessEpisode'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoteSearchAnimes(arg1) {
  return window['go']['main']['App']['RemoteSearchAnimes'](arg1);
}

export function RemoteSearchTorrents(arg1, arg2) {
  return window['go']['main']['App']['RemoteSearchTorrents'](arg1, arg2);
}

export function RemoveExtensionRepository(arg1) {
  return window['go']['main']['App']['RemoveExtensionRepository'](arg1);
}

export function RemoveFriend(arg1) {
  return window['go']['main']['App']['RemoveFriend'](arg1);
}

export function RemoveFromFavorites(arg1) {
  return window['go']['main']['App']['RemoveFromFavorites'](arg1);
}

export function ResetMangaSources() {
  return window['go']['main']['App']['ResetMangaSources']();
}

export function ResetSourceFailures() {
  return window['go']['main']['App']['ResetSourceFailures']();
}

export function ResetStreamCircuits() {
  return window['go']['main']['App']['ResetStreamCircuits']();
}

export function SaveDiscordConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveDiscordConfig'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchAniList(arg1, arg2) {
  return window['go']['main']['App']['SearchAniList'](arg1, arg2);
}

export function SearchConsumet(arg1) {
  return window['go']['main']['App']['SearchConsumet'](arg1);
}

export function SearchEnime(arg1) {
  return window['go']['main']['App']['SearchEnime'](arg1);
}

export function SearchMangas(arg1) {
  return window['go']['main']['App']['SearchMangas'](arg1);
}

export function SearchMangasAllSources(arg1) {
  return window['go']['main']['App']['SearchMangasAllSources'](arg1);
}

export function SearchMangasFromSource(arg1, arg2) {
  return window['go']['main']['App']['SearchMangasFromSource'](arg1, arg2);
}

export function SearchTorrents(arg1, arg2) {
  return window['go']['main']['App']['SearchTorrents'](arg1, arg2);
}

export function SearchTorrentsAll(arg1) {
  return window['go']['main']['App']['SearchTorrentsAll'](arg1);
}

export function SearchTorrentsBR(arg1) {
  return window['go']['main']['App']['SearchTorrentsBR'](arg1);
}

export function SearchTorrentsNyaa(arg1) {
  return window['go']['main']['App']['SearchTorrentsNyaa'](arg1);
}

export function SearchWithExtension(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchWithExtension'](arg1, arg2, arg3);
}

export function SendDiscordRecommendation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendDiscordRecommendation'](arg1, arg2, arg3, arg4);
}

export function SetDiscordClientSecret(arg1) {
  return window['go']['main']['App']['SetDiscordClientSecret'](arg1);
}

export function SetDiscordShareAnimes(arg1) {
  return window['go']['main']['App']['SetDiscordShareAnimes'](arg1);
}

export function SetDiscordShowStatus(arg1) {
  return window['go']['main']['App']['SetDiscordShowStatus'](arg1);
}

export function SetFullscreen(arg1) {
  return window['go']['main']['App']['SetFullscreen'](arg1);
}

export function SetSocialShareAnimes(arg1) {
  return window['go']['main']['App']['SetSocialShareAnimes'](arg1);
}

export function SetSocialShowStatus(arg1) {
  return window['go']['main']['App']['SetSocialShowStatus'](arg1);
}

export function SetStreamCache(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetStreamCache'](arg1, arg2, arg3, arg4);
}

export function SimulateDiscordConnect() {
  return window['go']['main']['App']['SimulateDiscordConnect']();
}

export function SkipEnding() {
  return window['go']['main']['App']['SkipEnding']();
}

export function SkipOpening() {
  return window['go']['main']['App']['SkipOpening']();
}

export function StartDiscordOAuth() {
  return window['go']['main']['App']['StartDiscordOAuth']();
}

export function StartSeeding() {
  return window['go']['main']['App']['StartSeeding']();
}

export function StopPlayer4K() {
  return window['go']['main']['App']['StopPlayer4K']();
}

export function StopSeeding() {
  return window['go']['main']['App']['StopSeeding']();
}

export function SyncSocialWithServer() {
  return window['go']['main']['App']['SyncSocialWithServer']();
}

export function ToggleExtension(arg1, arg2) {
  return window['go']['main']['App']['ToggleExtension'](arg1, arg2);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function ToggleMangaSource(arg1, arg2) {
  return window['go']['main']['App']['ToggleMangaSource'](arg1, arg2);
}

export function ToggleSeeding(arg1) {
  return window['go']['main']['App']['ToggleSeeding'](arg1);
}

export function TorBoxAddMagnet(arg1) {
  return window['go']['main']['App']['TorBoxAddMagnet'](arg1);
}

export function TorBoxCheckCached(arg1) {
  return window['go']['main']['App']['TorBoxCheckCached'](arg1);
}

export function TorBoxClearCache() {
  return window['go']['main']['App']['TorBoxClearCache']();
}

export function TorBoxDeleteTorrent(arg1) {
  return window['go']['main']['App']['TorBoxDeleteTorrent'](arg1);
}

export function TorBoxGetDownloadLink(arg1, arg2) {
  return window['go']['main']['App']['TorBoxGetDownloadLink'](arg1, arg2);
}

export function TorBoxGetFileStreamURL(arg1, arg2) {
  return window['go']['main']['App']['TorBoxGetFileStreamURL'](arg1, arg2);
}

export function TorBoxGetFilesFromMagnet(arg1) {
  return window['go']['main']['App']['TorBoxGetFilesFromMagnet'](arg1);
}

export function TorBoxGetInstantStream(arg1) {
  return window['go']['main']['App']['TorBoxGetInstantStream'](arg1);
}

export function TorBoxGetStreamLinkLocal(arg1, arg2) {
  return window['go']['main']['App']['TorBoxGetStreamLinkLocal'](arg1, arg2);
}

export function TorBoxGetTorrentFiles(arg1, arg2) {
  return window['go']['main']['App']['TorBoxGetTorrentFiles'](arg1, arg2);
}

export function TorBoxGetTorrents() {
  return window['go']['main']['App']['TorBoxGetTorrents']();
}

export function TorBoxGetUser() {
  return window['go']['main']['App']['TorBoxGetUser']();
}

export function TorBoxSearchAnimes(arg1) {
  return window['go']['main']['App']['TorBoxSearchAnimes'](arg1);
}

export function TorBoxSearchTorrents(arg1) {
  return window['go']['main']['App']['TorBoxSearchTorrents'](arg1);
}

export function TorBoxStreamAnimeEpisode(arg1, arg2, arg3) {
  return window['go']['main']['App']['TorBoxStreamAnimeEpisode'](arg1, arg2, arg3);
}

export function TorBoxStreamMagnet(arg1, arg2) {
  return window['go']['main']['App']['TorBoxStreamMagnet'](arg1, arg2);
}

export function UninstallExtension(arg1) {
  return window['go']['main']['App']['UninstallExtension'](arg1);
}

export function UnlinkDiscord() {
  return window['go']['main']['App']['UnlinkDiscord']();
}

export function UpdateDiscordWatchingStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateDiscordWatchingStatus'](arg1, arg2, arg3, arg4);
}

export function UpdateSocialUsername(arg1) {
  return window['go']['main']['App']['UpdateSocialUsername'](arg1);
}

export function UpdateSocialWatchingStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSocialWatchingStatus'](arg1, arg2, arg3, arg4);
}

export function VPSCheckHealth() {
  return window['go']['main']['App']['VPSCheckHealth']();
}

export function VPSDownloadSubtitle(arg1, arg2) {
  return window['go']['main']['App']['VPSDownloadSubtitle'](arg1, arg2);
}

export function VPSGetBestSubtitle(arg1, arg2) {
  return window['go']['main']['App']['VPSGetBestSubtitle'](arg1, arg2);
}

export function VPSGetEpisodeGoFile(arg1, arg2) {
  return window['go']['main']['App']['VPSGetEpisodeGoFile'](arg1, arg2);
}

export function VPSGetStreamURL(arg1) {
  return window['go']['main']['App']['VPSGetStreamURL'](arg1);
}

export function VPSSearchStream(arg1) {
  return window['go']['main']['App']['VPSSearchStream'](arg1);
}

export function VPSSearchSubtitles(arg1, arg2) {
  return window['go']['main']['App']['VPSSearchSubtitles'](arg1, arg2);
}

export function VPSStartPipeline(arg1, arg2, arg3) {
  return window['go']['main']['App']['VPSStartPipeline'](arg1, arg2, arg3);
}

export function ValidateStreamURL(arg1) {
  return window['go']['main']['App']['ValidateStreamURL'](arg1);
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowUnmaximise() {
  return window['go']['main']['App']['WindowUnmaximise']();
}
