// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToFavorites(arg1) {
  return window['go']['main']['App']['AddToFavorites'](arg1);
}

export function AddToWatchHistory(arg1) {
  return window['go']['main']['App']['AddToWatchHistory'](arg1);
}

export function AssistirEpisodio(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssistirEpisodio'](arg1, arg2, arg3);
}

export function BuscarAnimes(arg1) {
  return window['go']['main']['App']['BuscarAnimes'](arg1);
}

export function BuscarAnimesMulti(arg1) {
  return window['go']['main']['App']['BuscarAnimesMulti'](arg1);
}

export function ClearAllCache() {
  return window['go']['main']['App']['ClearAllCache']();
}

export function ClearEpisodesCache() {
  return window['go']['main']['App']['ClearEpisodesCache']();
}

export function CompleteDiscordOAuthWithCode(arg1) {
  return window['go']['main']['App']['CompleteDiscordOAuthWithCode'](arg1);
}

export function ConnectDiscord(arg1) {
  return window['go']['main']['App']['ConnectDiscord'](arg1);
}

export function CreateUser(arg1, arg2) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2);
}

export function DisconnectDiscord() {
  return window['go']['main']['App']['DisconnectDiscord']();
}

export function DisconnectDiscordUser() {
  return window['go']['main']['App']['DisconnectDiscordUser']();
}

export function ExportUserData() {
  return window['go']['main']['App']['ExportUserData']();
}

export function GenerateDiscordLinkCode() {
  return window['go']['main']['App']['GenerateDiscordLinkCode']();
}

export function GetAlternativeSource(arg1) {
  return window['go']['main']['App']['GetAlternativeSource'](arg1);
}

export function GetAnimeHDImage(arg1) {
  return window['go']['main']['App']['GetAnimeHDImage'](arg1);
}

export function GetAnimeURL(arg1) {
  return window['go']['main']['App']['GetAnimeURL'](arg1);
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetConsumetEpisodes(arg1, arg2) {
  return window['go']['main']['App']['GetConsumetEpisodes'](arg1, arg2);
}

export function GetConsumetStream(arg1, arg2) {
  return window['go']['main']['App']['GetConsumetStream'](arg1, arg2);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDiscordConfigStatus() {
  return window['go']['main']['App']['GetDiscordConfigStatus']();
}

export function GetDiscordFriendsActivity() {
  return window['go']['main']['App']['GetDiscordFriendsActivity']();
}

export function GetDiscordLinkStatus() {
  return window['go']['main']['App']['GetDiscordLinkStatus']();
}

export function GetDiscordOAuthURL() {
  return window['go']['main']['App']['GetDiscordOAuthURL']();
}

export function GetDiscordRecommendations() {
  return window['go']['main']['App']['GetDiscordRecommendations']();
}

export function GetDiscordServerInvite() {
  return window['go']['main']['App']['GetDiscordServerInvite']();
}

export function GetDiscordStatus() {
  return window['go']['main']['App']['GetDiscordStatus']();
}

export function GetDiscordUser() {
  return window['go']['main']['App']['GetDiscordUser']();
}

export function GetEnimeStream(arg1, arg2) {
  return window['go']['main']['App']['GetEnimeStream'](arg1, arg2);
}

export function GetEpisodes(arg1) {
  return window['go']['main']['App']['GetEpisodes'](arg1);
}

export function GetEpisodesForSource(arg1, arg2) {
  return window['go']['main']['App']['GetEpisodesForSource'](arg1, arg2);
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetPopularAnimes(arg1) {
  return window['go']['main']['App']['GetPopularAnimes'](arg1);
}

export function GetProxyURLForVideo(arg1) {
  return window['go']['main']['App']['GetProxyURLForVideo'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkipTimes(arg1, arg2) {
  return window['go']['main']['App']['GetSkipTimes'](arg1, arg2);
}

export function GetSkipTimesAsync(arg1, arg2) {
  return window['go']['main']['App']['GetSkipTimesAsync'](arg1, arg2);
}

export function GetSmartStream(arg1, arg2) {
  return window['go']['main']['App']['GetSmartStream'](arg1, arg2);
}

export function GetSmartStreamParallel(arg1, arg2) {
  return window['go']['main']['App']['GetSmartStreamParallel'](arg1, arg2);
}

export function GetStreamSourceStats() {
  return window['go']['main']['App']['GetStreamSourceStats']();
}

export function GetStreamURLForEpisode(arg1, arg2) {
  return window['go']['main']['App']['GetStreamURLForEpisode'](arg1, arg2);
}

export function GetStreamWithFallback(arg1, arg2) {
  return window['go']['main']['App']['GetStreamWithFallback'](arg1, arg2);
}

export function GetTopAnimes() {
  return window['go']['main']['App']['GetTopAnimes']();
}

export function GetTrendingAnimes(arg1) {
  return window['go']['main']['App']['GetTrendingAnimes'](arg1);
}

export function GetValidatedStreamCache(arg1) {
  return window['go']['main']['App']['GetValidatedStreamCache'](arg1);
}

export function GetWatchHistory() {
  return window['go']['main']['App']['GetWatchHistory']();
}

export function ImportUserData(arg1) {
  return window['go']['main']['App']['ImportUserData'](arg1);
}

export function InvalidateStreamCache(arg1) {
  return window['go']['main']['App']['InvalidateStreamCache'](arg1);
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function IsSourceAvailable(arg1) {
  return window['go']['main']['App']['IsSourceAvailable'](arg1);
}

export function LikeDiscordRecommendation(arg1) {
  return window['go']['main']['App']['LikeDiscordRecommendation'](arg1);
}

export function LinkDiscordWithCode(arg1) {
  return window['go']['main']['App']['LinkDiscordWithCode'](arg1);
}

export function PlayAnime(arg1) {
  return window['go']['main']['App']['PlayAnime'](arg1);
}

export function PlayVideo(arg1, arg2) {
  return window['go']['main']['App']['PlayVideo'](arg1, arg2);
}

export function RemoveFromFavorites(arg1) {
  return window['go']['main']['App']['RemoveFromFavorites'](arg1);
}

export function ResetSourceFailures() {
  return window['go']['main']['App']['ResetSourceFailures']();
}

export function ResetStreamCircuits() {
  return window['go']['main']['App']['ResetStreamCircuits']();
}

export function SaveDiscordConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveDiscordConfig'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchAniList(arg1, arg2) {
  return window['go']['main']['App']['SearchAniList'](arg1, arg2);
}

export function SearchConsumet(arg1) {
  return window['go']['main']['App']['SearchConsumet'](arg1);
}

export function SearchEnime(arg1) {
  return window['go']['main']['App']['SearchEnime'](arg1);
}

export function SendDiscordRecommendation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendDiscordRecommendation'](arg1, arg2, arg3, arg4);
}

export function SetDiscordClientSecret(arg1) {
  return window['go']['main']['App']['SetDiscordClientSecret'](arg1);
}

export function SetDiscordShareAnimes(arg1) {
  return window['go']['main']['App']['SetDiscordShareAnimes'](arg1);
}

export function SetDiscordShowStatus(arg1) {
  return window['go']['main']['App']['SetDiscordShowStatus'](arg1);
}

export function SetFullscreen(arg1) {
  return window['go']['main']['App']['SetFullscreen'](arg1);
}

export function SetStreamCache(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetStreamCache'](arg1, arg2, arg3, arg4);
}

export function SimulateDiscordConnect() {
  return window['go']['main']['App']['SimulateDiscordConnect']();
}

export function StartDiscordOAuth() {
  return window['go']['main']['App']['StartDiscordOAuth']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function UnlinkDiscord() {
  return window['go']['main']['App']['UnlinkDiscord']();
}

export function UpdateDiscordWatchingStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateDiscordWatchingStatus'](arg1, arg2, arg3, arg4);
}

export function ValidateStreamURL(arg1) {
  return window['go']['main']['App']['ValidateStreamURL'](arg1);
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowUnmaximise() {
  return window['go']['main']['App']['WindowUnmaximise']();
}
