// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';
import {time} from '../models';

export function AddToFavorites(arg1:store.SavedAnime):Promise<boolean>;

export function AddToWatchHistory(arg1:store.WatchedEpisode):Promise<void>;

export function AssistirEpisodio(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BuscarAnimes(arg1:string):Promise<Array<store.SavedAnime>>;

export function BuscarAnimesMulti(arg1:Array<string>):Promise<Array<store.SavedAnime>>;

export function ClearAllCache():Promise<void>;

export function ClearEpisodesCache():Promise<void>;

export function CompleteDiscordOAuthWithCode(arg1:string):Promise<main.DiscordUserInfo>;

export function ConnectDiscord(arg1:string):Promise<void>;

export function CreateUser(arg1:string,arg2:string):Promise<store.UserData>;

export function DisconnectDiscord():Promise<void>;

export function DisconnectDiscordUser():Promise<void>;

export function ExportUserData():Promise<string>;

export function GenerateDiscordLinkCode():Promise<string>;

export function GetAllMangas(arg1:number):Promise<main.MangaListResult>;

export function GetAllMangasAdult():Promise<Array<main.MangaInfo>>;

export function GetAllMangasComplete():Promise<Array<main.MangaInfo>>;

export function GetAllMangasFromSourceComplete(arg1:string):Promise<Array<main.MangaInfo>>;

export function GetAllMangasSafe():Promise<Array<main.MangaInfo>>;

export function GetAlternativeSource(arg1:Array<string>):Promise<string>;

export function GetAnimeHDImage(arg1:string):Promise<Record<string, string>>;

export function GetAnimeURL(arg1:string):Promise<string>;

export function GetCacheStats():Promise<main.CacheStats>;

export function GetChapterPages(arg1:string):Promise<Array<main.MangaPageInfo>>;

export function GetChapterPagesAuto(arg1:string):Promise<Array<main.MangaPageInfo>>;

export function GetConsumetEpisodes(arg1:string,arg2:string):Promise<Array<main.ConsumetEpisode>>;

export function GetConsumetStream(arg1:string,arg2:string):Promise<string>;

export function GetCurrentUser():Promise<store.UserData>;

export function GetDiscordConfigStatus():Promise<Record<string, any>>;

export function GetDiscordFriendsActivity():Promise<Array<main.DiscordFriendActivity>>;

export function GetDiscordLinkStatus():Promise<main.DiscordLinkInfo>;

export function GetDiscordOAuthURL():Promise<string>;

export function GetDiscordRecommendations():Promise<Array<main.DiscordRecommendation>>;

export function GetDiscordServerInvite():Promise<string>;

export function GetDiscordStatus():Promise<main.DiscordStatus>;

export function GetDiscordUser():Promise<main.DiscordUserInfo>;

export function GetEnimeStream(arg1:string,arg2:number):Promise<string>;

export function GetEpisodes(arg1:string):Promise<Array<store.Episode>>;

export function GetEpisodesForSource(arg1:string,arg2:string):Promise<Array<store.Episode>>;

export function GetFavorites():Promise<Array<store.SavedAnime>>;

export function GetFeaturedMangas(arg1:number):Promise<Array<main.MangaInfo>>;

export function GetFeaturedMangasFromSource(arg1:number,arg2:string):Promise<Array<main.MangaInfo>>;

export function GetLatestMangas():Promise<Array<main.MangaInfo>>;

export function GetLatestMangasFromSource(arg1:string):Promise<Array<main.MangaInfo>>;

export function GetMangaChapters(arg1:string):Promise<Array<main.MangaChapterInfo>>;

export function GetMangaChaptersAuto(arg1:string):Promise<Array<main.MangaChapterInfo>>;

export function GetMangaDetails(arg1:string):Promise<main.MangaInfo>;

export function GetMangaDetailsAuto(arg1:string):Promise<main.MangaInfo>;

export function GetMangaGenres():Promise<Array<string>>;

export function GetMangaSources():Promise<Array<string>>;

export function GetMangaSourcesInfo():Promise<Array<main.MangaSourceInfo>>;

export function GetMangasByGenre(arg1:string):Promise<Array<main.MangaInfo>>;

export function GetMangasFromAllSources(arg1:number):Promise<main.MangaListResult>;

export function GetMangasFromSource(arg1:string,arg2:number):Promise<main.MangaListResult>;

export function GetMergedMangas(arg1:number):Promise<Array<main.MangaInfo>>;

export function GetMergedMangasComplete():Promise<Array<main.MangaInfo>>;

export function GetMergedMangasWithBestSource():Promise<Array<main.MangaInfo>>;

export function GetPopularAnimes(arg1:number):Promise<Array<main.AniListAnime>>;

export function GetPopularMangas():Promise<Array<main.MangaInfo>>;

export function GetPopularMangasAdult():Promise<Array<main.MangaInfo>>;

export function GetPopularMangasAllSources():Promise<Array<main.MangaInfo>>;

export function GetPopularMangasFromSource(arg1:string):Promise<Array<main.MangaInfo>>;

export function GetPopularMangasSafe():Promise<Array<main.MangaInfo>>;

export function GetProxyURLForVideo(arg1:string):Promise<string>;

export function GetSettings():Promise<store.UserSettings>;

export function GetSkipTimes(arg1:number,arg2:number):Promise<main.SkipTimesResult>;

export function GetSkipTimesAsync(arg1:number,arg2:number):Promise<void>;

export function GetSmartStream(arg1:string,arg2:number):Promise<main.SmartStreamResult>;

export function GetSmartStreamParallel(arg1:string,arg2:number):Promise<main.SmartStreamResult>;

export function GetStreamSourceStats():Promise<Record<string, any>>;

export function GetStreamURLForEpisode(arg1:string,arg2:string):Promise<string>;

export function GetStreamWithFallback(arg1:string,arg2:number):Promise<string>;

export function GetTopAnimes():Promise<Array<store.SavedAnime>>;

export function GetTrendingAnimes(arg1:number):Promise<Array<main.AniListAnime>>;

export function GetValidatedStreamCache(arg1:string):Promise<string|boolean>;

export function GetWatchHistory():Promise<Array<store.WatchedEpisode>>;

export function ImportUserData(arg1:string):Promise<void>;

export function InvalidateStreamCache(arg1:string):Promise<void>;

export function IsFavorite(arg1:string):Promise<boolean>;

export function IsSourceAvailable(arg1:string):Promise<boolean>;

export function LikeDiscordRecommendation(arg1:string):Promise<boolean>;

export function LinkDiscordWithCode(arg1:string):Promise<main.DiscordLinkInfo>;

export function PlayAnime(arg1:string):Promise<void>;

export function PlayVideo(arg1:string,arg2:string):Promise<void>;

export function RemoveFromFavorites(arg1:string):Promise<boolean>;

export function ResetSourceFailures():Promise<void>;

export function ResetStreamCircuits():Promise<void>;

export function SaveDiscordConfig(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:store.UserSettings):Promise<boolean>;

export function SearchAniList(arg1:string,arg2:number):Promise<Array<main.AniListAnime>>;

export function SearchConsumet(arg1:string):Promise<Array<main.ConsumetAnime>>;

export function SearchEnime(arg1:string):Promise<Array<main.EnimeAnime>>;

export function SearchMangas(arg1:string):Promise<Array<main.MangaInfo>>;

export function SearchMangasAllSources(arg1:string):Promise<Array<main.MangaInfo>>;

export function SearchMangasFromSource(arg1:string,arg2:string):Promise<Array<main.MangaInfo>>;

export function SendDiscordRecommendation(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function SetDiscordClientSecret(arg1:string):Promise<void>;

export function SetDiscordShareAnimes(arg1:boolean):Promise<void>;

export function SetDiscordShowStatus(arg1:boolean):Promise<void>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function SetStreamCache(arg1:string,arg2:string,arg3:string,arg4:time.Duration):Promise<void>;

export function SimulateDiscordConnect():Promise<void>;

export function StartDiscordOAuth():Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function UnlinkDiscord():Promise<void>;

export function UpdateDiscordWatchingStatus(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function ValidateStreamURL(arg1:string):Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowUnmaximise():Promise<void>;
